version: '3.9'

services:
  nestjs_postgres:
    container_name: bib_postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
    - ./db/initdb.d:/docker-entrypoint-initdb.d
    - ./data/postgres:/data/postgres
    env_file:
    - docker.env
 
