version: '3.9'

services:
  bib_postgres:
    container_name: bib_postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
    - ./data/postgres:/data/postgres
    env_file:
    - .env
    networks:
    - breakfastinbed

  pgadmin:
      links:
      - bib_postgres:bib_postgres
      container_name: pgadmin
      image: dpage/pgadmin4
      ports:
      - "8088:80"
      volumes:
      - ./data/pgadmin:/root/.pgadmin
      env_file:
      - .env
      networks:
      - breakfastinbed
      depends_on:
        - bib_postgres
networks:
  breakfastinbed:
    driver: bridge