import { RegisterDto } from 'src/auth/dto/register.dto';

export const users: RegisterDto[] = [
  {
    firstname: 'Alea',
    lastname: 'Lara',
    email: 'sagittis.duis@hotmail.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Shannon',
    lastname: 'Russell',
    email: 'tortor.integer.aliquam@aol.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Ava',
    lastname: 'Glass',
    email: 'sem.semper@yahoo.org',
    password: '1testPassword',
  },
  {
    firstname: 'Jared',
    lastname: 'Dean',
    email: 'arcu@icloud.net',
    password: '1testPassword',
  },
  {
    firstname: 'Cameron',
    lastname: 'Larson',
    email: 'lacinia.at@yahoo.net',
    password: '1testPassword',
  },
  {
    firstname: 'Chaney',
    lastname: 'Best',
    email: 'ultricies@outlook.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Colton',
    lastname: 'Britt',
    email: 'arcu.aliquam@protonmail.com',
    password: '1testPassword',
  },
  {
    firstname: 'Nola',
    lastname: 'Shepherd',
    email: 'scelerisque@google.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Jasmine',
    lastname: 'Brewer',
    email: 'nascetur.ridiculus@yahoo.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Dane',
    lastname: 'Harding',
    email: 'facilisis.vitae@protonmail.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Emerald',
    lastname: 'Mcclain',
    email: 'ante@yahoo.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Murphy',
    lastname: 'Erickson',
    email: 'non.lorem@aol.net',
    password: '1testPassword',
  },
  {
    firstname: 'Debra',
    lastname: 'Medina',
    email: 'sagittis.nullam@google.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Helen',
    lastname: 'Castillo',
    email: 'at.risus.nunc@google.com',
    password: '1testPassword',
  },
  {
    firstname: 'Kuame',
    lastname: 'Holman',
    email: 'metus.eu@icloud.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Sopoline',
    lastname: 'Bell',
    email: 'dui.lectus.rutrum@google.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Ira',
    lastname: 'Jacobson',
    email: 'orci.tincidunt.adipiscing@yahoo.org',
    password: '1testPassword',
  },
  {
    firstname: 'Levi',
    lastname: 'Hutchinson',
    email: 'et.nunc@aol.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Brenda',
    lastname: 'Lang',
    email: 'sagittis.duis@google.com',
    password: '1testPassword',
  },
  {
    firstname: 'Mohammad',
    lastname: 'Rodriquez',
    email: 'porttitor@yahoo.com',
    password: '1testPassword',
  },
  {
    firstname: 'Athena',
    lastname: 'Santana',
    email: 'nam.ac.nulla@yahoo.com',
    password: '1testPassword',
  },
  {
    firstname: 'Quamar',
    lastname: 'Stephens',
    email: 'nulla@hotmail.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Yoko',
    lastname: 'Aguirre',
    email: 'aliquet@aol.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Karyn',
    lastname: 'Bentley',
    email: 'posuere.at@aol.net',
    password: '1testPassword',
  },
  {
    firstname: 'Marny',
    lastname: 'Hanson',
    email: 'sed@hotmail.net',
    password: '1testPassword',
  },
  {
    firstname: 'Simone',
    lastname: 'Quinn',
    email: 'aliquet.odio@google.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Adria',
    lastname: 'Conley',
    email: 'neque.morbi.quis@icloud.org',
    password: '1testPassword',
  },
  {
    firstname: 'Veda',
    lastname: 'Cervantes',
    email: 'aliquam.iaculis@hotmail.net',
    password: '1testPassword',
  },
  {
    firstname: 'Vaughan',
    lastname: 'Harrison',
    email: 'adipiscing.lacus@aol.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Gannon',
    lastname: 'Reed',
    email: 'et@outlook.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Sydnee',
    lastname: 'Warren',
    email: 'sollicitudin@aol.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Galvin',
    lastname: 'Kennedy',
    email: 'faucibus.ut.nulla@aol.com',
    password: '1testPassword',
  },
  {
    firstname: 'Victoria',
    lastname: 'Barker',
    email: 'sit.amet.orci@google.org',
    password: '1testPassword',
  },
  {
    firstname: 'Portia',
    lastname: 'Tillman',
    email: 'risus.in@google.org',
    password: '1testPassword',
  },
  {
    firstname: 'Anjolie',
    lastname: 'Mcfarland',
    email: 'nunc.est@aol.com',
    password: '1testPassword',
  },
  {
    firstname: 'Hammett',
    lastname: 'Brown',
    email: 'rutrum.justo.praesent@hotmail.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Jonah',
    lastname: 'Byers',
    email: 'augue.sed@yahoo.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Sybill',
    lastname: 'Bowman',
    email: 'parturient.montes@aol.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Russell',
    lastname: 'Bean',
    email: 'mi.felis.adipiscing@yahoo.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Conan',
    lastname: 'Wilcox',
    email: 'pharetra@hotmail.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Lacota',
    lastname: 'Massey',
    email: 'nibh.lacinia@aol.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Ifeoma',
    lastname: 'Velez',
    email: 'fames.ac@protonmail.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Ethan',
    lastname: 'Blackwell',
    email: 'gravida.sit.amet@hotmail.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Noelani',
    lastname: 'Hayden',
    email: 'suspendisse@protonmail.net',
    password: '1testPassword',
  },
  {
    firstname: 'Hakeem',
    lastname: 'Wilkins',
    email: 'nulla.vulputate@icloud.net',
    password: '1testPassword',
  },
  {
    firstname: 'Vivian',
    lastname: 'Shaw',
    email: 'urna.nec@yahoo.com',
    password: '1testPassword',
  },
  {
    firstname: 'Kirk',
    lastname: 'Hewitt',
    email: 'sit.amet.diam@outlook.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Olga',
    lastname: 'Hill',
    email: 'non.dapibus.rutrum@protonmail.net',
    password: '1testPassword',
  },
  {
    firstname: 'Serina',
    lastname: 'Conner',
    email: 'mi.eleifend@protonmail.net',
    password: '1testPassword',
  },
  {
    firstname: 'Alden',
    lastname: 'Jones',
    email: 'tempus.mauris.erat@aol.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Mason',
    lastname: 'Huffman',
    email: 'aliquet@hotmail.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Guinevere',
    lastname: 'Nguyen',
    email: 'convallis.convallis@aol.com',
    password: '1testPassword',
  },
  {
    firstname: 'Desirae',
    lastname: 'Eaton',
    email: 'mauris.suspendisse@icloud.net',
    password: '1testPassword',
  },
  {
    firstname: 'Rashad',
    lastname: 'Kim',
    email: 'lectus.a.sollicitudin@yahoo.org',
    password: '1testPassword',
  },
  {
    firstname: 'Cairo',
    lastname: 'Wallace',
    email: 'molestie@google.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Rina',
    lastname: 'Pope',
    email: 'vel.quam.dignissim@aol.com',
    password: '1testPassword',
  },
  {
    firstname: 'Sybill',
    lastname: 'Sharpe',
    email: 'porttitor.tellus.non@google.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Blake',
    lastname: 'Cooper',
    email: 'vulputate.lacus@google.net',
    password: '1testPassword',
  },
  {
    firstname: 'Patricia',
    lastname: 'Dejesus',
    email: 'libero@icloud.net',
    password: '1testPassword',
  },
  {
    firstname: 'Armand',
    lastname: 'Wilkerson',
    email: 'dolor.quisque.tincidunt@outlook.net',
    password: '1testPassword',
  },
  {
    firstname: 'Briar',
    lastname: 'Fuentes',
    email: 'sem.nulla@hotmail.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Martina',
    lastname: 'Harding',
    email: 'ut.sem@yahoo.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Fritz',
    lastname: 'Brock',
    email: 'ante.dictum.cursus@google.net',
    password: '1testPassword',
  },
  {
    firstname: 'Phoebe',
    lastname: 'Roy',
    email: 'libero.mauris@google.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Halee',
    lastname: 'Hunter',
    email: 'consectetuer@protonmail.net',
    password: '1testPassword',
  },
  {
    firstname: 'Phoebe',
    lastname: 'Valenzuela',
    email: 'vitae.nibh@aol.net',
    password: '1testPassword',
  },
  {
    firstname: 'Camilla',
    lastname: 'Roy',
    email: 'tincidunt@google.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Laith',
    lastname: 'Hartman',
    email: 'taciti.sociosqu@icloud.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Burton',
    lastname: 'Gregory',
    email: 'diam.sed@outlook.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Moses',
    lastname: 'Best',
    email: 'neque.non@google.net',
    password: '1testPassword',
  },
  {
    firstname: 'Allistair',
    lastname: 'Ingram',
    email: 'purus.in@yahoo.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Cherokee',
    lastname: 'Alexander',
    email: 'ornare.libero.at@google.net',
    password: '1testPassword',
  },
  {
    firstname: 'Illiana',
    lastname: 'Durham',
    email: 'vel.mauris.integer@google.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Aladdin',
    lastname: 'Goff',
    email: 'cras.interdum@google.net',
    password: '1testPassword',
  },
  {
    firstname: 'Berk',
    lastname: 'Ellison',
    email: 'nisl@outlook.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Noble',
    lastname: 'Howell',
    email: 'aliquam.nisl.nulla@outlook.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Reece',
    lastname: 'Gilbert',
    email: 'at.auctor@google.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Mallory',
    lastname: 'Riley',
    email: 'convallis@yahoo.net',
    password: '1testPassword',
  },
  {
    firstname: 'Nigel',
    lastname: 'Kline',
    email: 'cursus.vestibulum@google.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Piper',
    lastname: 'Perry',
    email: 'eu.tellus@google.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Channing',
    lastname: 'Winters',
    email: 'ornare.facilisis.eget@icloud.org',
    password: '1testPassword',
  },
  {
    firstname: 'Hilel',
    lastname: 'Atkins',
    email: 'fusce.feugiat.lorem@aol.net',
    password: '1testPassword',
  },
  {
    firstname: 'Kellie',
    lastname: 'Battle',
    email: 'semper.tellus@yahoo.net',
    password: '1testPassword',
  },
  {
    firstname: 'Shelley',
    lastname: 'Macias',
    email: 'aliquet.nec@aol.org',
    password: '1testPassword',
  },
  {
    firstname: 'Nomlanga',
    lastname: 'Byers',
    email: 'ornare.egestas@google.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Graiden',
    lastname: 'Holder',
    email: 'imperdiet.non@protonmail.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Victoria',
    lastname: 'Goodwin',
    email: 'semper@hotmail.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Cadman',
    lastname: 'Cobb',
    email: 'ullamcorper@icloud.com',
    password: '1testPassword',
  },
  {
    firstname: 'Chase',
    lastname: 'Cherry',
    email: 'vulputate@google.org',
    password: '1testPassword',
  },
  {
    firstname: 'Clementine',
    lastname: 'Chan',
    email: 'orci.ut@google.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Sierra',
    lastname: 'Wheeler',
    email: 'velit.eget@protonmail.org',
    password: '1testPassword',
  },
  {
    firstname: 'Octavia',
    lastname: 'Bowman',
    email: 'sit.amet.massa@outlook.ca',
    password: '1testPassword',
  },
  {
    firstname: 'Patrick',
    lastname: 'Bennett',
    email: 'a.odio@aol.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Rajah',
    lastname: 'Wong',
    email: 'ante.dictum@icloud.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Wynne',
    lastname: 'Wheeler',
    email: 'bibendum.ullamcorper.duis@aol.net',
    password: '1testPassword',
  },
  {
    firstname: 'Declan',
    lastname: 'Buchanan',
    email: 'vivamus.non.lorem@google.couk',
    password: '1testPassword',
  },
  {
    firstname: 'Jessica',
    lastname: 'Preston',
    email: 'nisl.elementum.purus@google.net',
    password: '1testPassword',
  },
  {
    firstname: 'Sage',
    lastname: 'House',
    email: 'dapibus.gravida.aliquam@outlook.com',
    password: '1testPassword',
  },
  {
    firstname: 'Daria',
    lastname: 'Osborne',
    email: 'duis.volutpat@hotmail.edu',
    password: '1testPassword',
  },
  {
    firstname: 'Lilah',
    lastname: 'Fischer',
    email: 'in@icloud.ca',
    password: '1testPassword',
  },
];
